# Generated by Django 3.2.5 on 2021-07-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='uploads/default.jpg', upload_to='uploads/'),
        ),
    ]
