# Generated by Django 3.1.4 on 2021-07-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20210717_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='uploads/default.jpg', upload_to='uploads/'),
        ),
    ]
